version: '3.8'

services:
  postgres-db:
    image: postgres:18-alpine
    container_name: my_postgres_container
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  backend-java:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/${DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - FINNHUB_API_KEY=${FINNHUB_API_KEY}
    depends_on:
      - postgres-db

  backend-python:
    build: ./analysis
    ports:
      - "8000:8000"
    volumes:
      - ./analysis:/app
    depends_on:
      - postgres-db

  frontend-react:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  postgres_data:
